package com.example.tinder_ai_backend.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

// Swagger url : http://localhost:8080/swagger-ui/index.html
// Openapi url : http://localhost:8080/swagger-ui/index.html

@Configuration
public class OpenAPIConfig {

    @Value("${spring.openapi.dev.url}")
    private String openApiDevServerUrl;

    @Value("${spring.openapi.prod.url}")
    private String openApiProdServerUrl;

    @Bean
    public OpenAPI openAPI() {

        Server devServer = new Server();
        devServer.setUrl(openApiDevServerUrl);

        Server prodServer = new Server();
        prodServer.setUrl(openApiProdServerUrl);

        Contact contact = new Contact()
                .name("JC Lucas")
                .email("jclucasasp@gmail.com");

        Info info = new Info()
                .title("AI Dating app")
                .version("1.0.0")
                .description("Everything is generated by AI")
                .contact(contact);

        return new OpenAPI()
                .info(info)
                .servers(List.of(devServer, prodServer));
    }
}
